services:
  postgres:
    image: postgres:16-alpine
    container_name: saas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2026
      POSTGRES_DB: dev_saas_backend
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    # HIGHLIGHT: The Healthcheck
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d dev_saas_backend']
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:16-alpine
    container_name: saas_db_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2026
      POSTGRES_DB: test_saas_backend
    ports:
      - '5436:5432'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    container_name: saas_api
    restart: always
    ports:
      - '5000:5000'
    environment:
  - PORT=${PORT}
  - DATABASE_URL=${DATABASE_URL}
  - NODE_ENV=${NODE_ENV}
  - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
  - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
  - MAIL_HOST=${MAIL_HOST}
  - MAIL_PORT=${MAIL_PORT}
  - MAIL_USER=${MAIL_USER}
  - MAIL_PASS=${MAIL_PASS}
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - AWS_REGION=${AWS_REGION}
  - AWS_S3_BUCKET=${AWS_S3_BUCKET}
  - SUPER_ADMIN_ACCESS_SECRET=${SUPER_ADMIN_ACCESS_SECRET}
  - SUPER_ADMIN_REFRESH_SECRET=${SUPER_ADMIN_REFRESH_SECRET}

    # HIGHLIGHT: Waiting for the DB to actually be READY
    volumes:
      - .:/app # Links your whole project folder to /app in Linux
      - /app/node_modules # Keeps node_modules inside Linux (prevents Windows conflicts)
      - /app/apps/api/node_modules
    command: npx tsx watch --tsconfig apps/api/tsconfig.json apps/api/src/index.ts
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
