services:
  postgres:
    image: postgres:16-alpine
    container_name: saas_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: saas_prod
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    # HIGHLIGHT: The Healthcheck
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d saas_prod']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    container_name: saas_api
    restart: always
    ports:
      - '5000:5000'
    environment:
      # HIGHLIGHT: Internal Network Hostname
      - PORT=5000
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/saas_prod?schema=public
      - NODE_ENV=development
      - PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK=1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

    # HIGHLIGHT: Waiting for the DB to actually be READY
    volumes:
      - .:/app # Links your whole project folder to /app in Linux
      - /app/node_modules # Keeps node_modules inside Linux (prevents Windows conflicts)
      - /app/apps/api/node_modules
    command: npx tsx watch --tsconfig apps/api/tsconfig.json apps/api/src/index.ts
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
