// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';

const root = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(root, '.env') });
dotenv.config({ path: path.join(root, '.env.development') });

const datasourceUrl = process.env.DATABASE_URL;
if (!datasourceUrl) {
  throw new Error(
    'DATABASE_URL is required in prisma.config.ts (set it in the environment or apps/api/.env)',
  );
}

export default defineConfig({
  schema: path.join(root, 'prisma/schema.prisma'),
  migrations: {
    path: path.join(root, 'prisma/migrations'),
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: datasourceUrl,
  },
});
